### ISSUE TITLE
to_reo cause errors if using with other WIN32APIs

### ISSUE THREAD

**Issue by dsisnero** [Thomas008/robust_excel_ole#34] opened 2021-03-17 21:07 UTC
I have a Rakefile where I use other WIN32OLE objects.  When trying to use the other object that mirrors one of the REO methods (save), I am getting a an exception because of this line
raise TypeREOError, "given object cannot be type-lifted to a RobustExcelOle object" .  This object isn't a RobustExcelOle object but the redefining of the save method is causing this exception

**Comment by Thomas008** [comment] 2021-03-20 13:22
Can you describe a bit more about the other WIN32OLE object, and what the mirroring the REO save method looks like?
The exception says probably that the object is not a win32ol object that is wrapped in RobustExcelOle.



 

---
Dr. Thomas Raths
Körperpsychotherapie, Kreativtherapie, WATSU

Friedenstraße 38
97072 Würzburg

0175 - 90 81 668
www.erlebens-raum.de

 
 

Gesendet: Mittwoch, 17. März 2021 um 22:07 Uhr
Von: "dsisnero" ***@***.***>
An: "Thomas008/robust_excel_ole" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [Thomas008/robust_excel_ole] to_reo cause errors if using with other WIN32APIs (#34)


 

I have a Rakefile where I use other WIN32OLE objects. When trying to use the other object that mirrors one of the REO methods (save), I am getting a an exception because of this line
raise TypeREOError, "given object cannot be type-lifted to a RobustExcelOle object" . This object isn't a RobustExcelOle object but the redefining of the save method is causing this exception

**Comment by Thomas008** [comment] 2021-03-24 20:55
Exporing this issue, we found that the bug is caused by a method General#init_reo_for_win32ole that defines RobustExcelOle methods for WIN32OLE objects (such that these methods are available for WIN32OLE objects, too). Here are some first solutions of this issue:
1. Can you define the save method starting with upper-case letter? Can you give feedback, if that works
2. In case there are several redefined methods starting with upper-case letter, in the last pushed version we implemented a version of the method General#init_reo_for_win32ole that should exclude redefined upper-case letter methods.
3. I will try a refinement such that using this method General#init_reo_for_win32ole can be controlled. We had problems with a first implementation with that.

I hope, this gives a first clue. Please send us feedback, whether this helps you. Thank you for pointing out this issue!

**Comment by dsisnero** [comment] 2021-03-30 21:16
I was able to call it using uppercase Save without an error.

**Comment by Thomas008** [comment] 2021-04-23 16:49
We have now fixed the problem. The methods in other WIn32OLE objects are now being preserved and not being overwritten.
Thank you for pointing this out.

**Closed by Thomas008** 2021-04-23 16:49 UTC
